//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookstore.Languages.Resources.", typeof(Resources_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolicina.
        /// </summary>
        internal static string AddArticleAmountTextBlock {
            get {
                return ResourceManager.GetString("AddArticleAmountTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Artikal.
        /// </summary>
        internal static string AddArticleButtonTextAdd {
            get {
                return ResourceManager.GetString("AddArticleButtonTextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azuriraj Artikal.
        /// </summary>
        internal static string AddArticleButtonTextUpdate {
            get {
                return ResourceManager.GetString("AddArticleButtonTextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string AddArticleDescriptionTextBlock {
            get {
                return ResourceManager.GetString("AddArticleDescriptionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string AddArticleNameTextBlock {
            get {
                return ResourceManager.GetString("AddArticleNameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        internal static string AddArticlePriceTextBlock {
            get {
                return ResourceManager.GetString("AddArticlePriceTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Autora.
        /// </summary>
        internal static string AddAuthorButtonTextAdd {
            get {
                return ResourceManager.GetString("AddAuthorButtonTextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azuriraj Autora.
        /// </summary>
        internal static string AddAuthorButtonTextUpdate {
            get {
                return ResourceManager.GetString("AddAuthorButtonTextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string AddAuthorNameTextBlock {
            get {
                return ResourceManager.GetString("AddAuthorNameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string AddAuthorSurnameTextBlock {
            get {
                return ResourceManager.GetString("AddAuthorSurnameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolicina.
        /// </summary>
        internal static string AddBookAmountTextBlock {
            get {
                return ResourceManager.GetString("AddBookAmountTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Knjigu.
        /// </summary>
        internal static string AddBookButtonTextAdd {
            get {
                return ResourceManager.GetString("AddBookButtonTextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azuriraj Knjigu.
        /// </summary>
        internal static string AddBookButtonTextUpdate {
            get {
                return ResourceManager.GetString("AddBookButtonTextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string AddBookDescriptionTextBlock {
            get {
                return ResourceManager.GetString("AddBookDescriptionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        internal static string AddBookISBNTextBlock {
            get {
                return ResourceManager.GetString("AddBookISBNTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        internal static string AddBookLanguageTextBlock {
            get {
                return ResourceManager.GetString("AddBookLanguageTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string AddBookNameTextBlock {
            get {
                return ResourceManager.GetString("AddBookNameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        internal static string AddBookPriceTextBlock {
            get {
                return ResourceManager.GetString("AddBookPriceTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izdavac.
        /// </summary>
        internal static string AddBookPublisherTextBlock {
            get {
                return ResourceManager.GetString("AddBookPublisherTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi Autore.
        /// </summary>
        internal static string AddBookSelectAuthorsTextBlock {
            get {
                return ResourceManager.GetString("AddBookSelectAuthorsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina Izdanja.
        /// </summary>
        internal static string AddBookYearOfIssueTextBlock {
            get {
                return ResourceManager.GetString("AddBookYearOfIssueTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina Objavljivanja.
        /// </summary>
        internal static string AddBookYearOfPublicationTextBlock {
            get {
                return ResourceManager.GetString("AddBookYearOfPublicationTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Zaposlenog.
        /// </summary>
        internal static string AddEmployeeButtonTextAdd {
            get {
                return ResourceManager.GetString("AddEmployeeButtonTextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azuriraj Zaposlenog.
        /// </summary>
        internal static string AddEmployeeButtonTextUpdate {
            get {
                return ResourceManager.GetString("AddEmployeeButtonTextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi Lozinku.
        /// </summary>
        internal static string AddEmployeeConfirmPasswordTextBlock {
            get {
                return ResourceManager.GetString("AddEmployeeConfirmPasswordTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko Ime.
        /// </summary>
        internal static string AddEmployeeNameTextBlock {
            get {
                return ResourceManager.GetString("AddEmployeeNameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        internal static string AddEmployeePasswordTextBlock {
            get {
                return ResourceManager.GetString("AddEmployeePasswordTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMB.
        /// </summary>
        internal static string AddEmployeeUINTextBlock {
            get {
                return ResourceManager.GetString("AddEmployeeUINTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Artikal.
        /// </summary>
        internal static string AddItemsButtonTextAddArticle {
            get {
                return ResourceManager.GetString("AddItemsButtonTextAddArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Autora.
        /// </summary>
        internal static string AddItemsButtonTextAddAuthor {
            get {
                return ResourceManager.GetString("AddItemsButtonTextAddAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Knjigu.
        /// </summary>
        internal static string AddItemsButtonTextAddBook {
            get {
                return ResourceManager.GetString("AddItemsButtonTextAddBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Izdavaca.
        /// </summary>
        internal static string AddItemsButtonTextAddPublisher {
            get {
                return ResourceManager.GetString("AddItemsButtonTextAddPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Izdavaca.
        /// </summary>
        internal static string AddPublisherButtonTextAdd {
            get {
                return ResourceManager.GetString("AddPublisherButtonTextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azuriraj Izdavaca.
        /// </summary>
        internal static string AddPublisherButtonTextUpdate {
            get {
                return ResourceManager.GetString("AddPublisherButtonTextUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string AddPublisherNameTextBlock {
            get {
                return ResourceManager.GetString("AddPublisherNameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikli.
        /// </summary>
        internal static string DatabaseComboItemArticles {
            get {
                return ResourceManager.GetString("DatabaseComboItemArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autori.
        /// </summary>
        internal static string DatabaseComboItemAuthors {
            get {
                return ResourceManager.GetString("DatabaseComboItemAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racuni.
        /// </summary>
        internal static string DatabaseComboItemBills {
            get {
                return ResourceManager.GetString("DatabaseComboItemBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knjige.
        /// </summary>
        internal static string DatabaseComboItemBooks {
            get {
                return ResourceManager.GetString("DatabaseComboItemBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izdavaci.
        /// </summary>
        internal static string DatabaseComboItemPublishers {
            get {
                return ResourceManager.GetString("DatabaseComboItemPublishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga....
        /// </summary>
        internal static string DatabaseSearchBarText {
            get {
                return ResourceManager.GetString("DatabaseSearchBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevalidni Kredencijali.
        /// </summary>
        internal static string LoginAuthenticationError {
            get {
                return ResourceManager.GetString("LoginAuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        internal static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste Registrovani.
        /// </summary>
        internal static string LoginNotRegisteredError {
            get {
                return ResourceManager.GetString("LoginNotRegisteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        internal static string LoginPasswordTextBlock {
            get {
                return ResourceManager.GetString("LoginPasswordTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        internal static string LoginTextBlock {
            get {
                return ResourceManager.GetString("LoginTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko Ime.
        /// </summary>
        internal static string LoginUsernameTextBlock {
            get {
                return ResourceManager.GetString("LoginUsernameTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Stavke.
        /// </summary>
        internal static string MainAddItemsButtonText {
            get {
                return ResourceManager.GetString("MainAddItemsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baza.
        /// </summary>
        internal static string MainDatabaseButtonText {
            get {
                return ResourceManager.GetString("MainDatabaseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rukovodi Nalozima.
        /// </summary>
        internal static string MainManageAccountsButtonText {
            get {
                return ResourceManager.GetString("MainManageAccountsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupi.
        /// </summary>
        internal static string MainPurchaseButtonText {
            get {
                return ResourceManager.GetString("MainPurchaseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Zaposlenog.
        /// </summary>
        internal static string ManageAccountsAddEmployeeButtonText {
            get {
                return ResourceManager.GetString("ManageAccountsAddEmployeeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled Zaposlenih.
        /// </summary>
        internal static string ManageAccountsViewEmployeesButtonText {
            get {
                return ResourceManager.GetString("ManageAccountsViewEmployeesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Racun.
        /// </summary>
        internal static string PurchaseAddBillButtonText {
            get {
                return ResourceManager.GetString("PurchaseAddBillButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Stavke.
        /// </summary>
        internal static string PurchaseAddBillItemButtonText {
            get {
                return ResourceManager.GetString("PurchaseAddBillItemButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolicina.
        /// </summary>
        internal static string PurchaseAmountTextBlock {
            get {
                return ResourceManager.GetString("PurchaseAmountTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikal.
        /// </summary>
        internal static string PurchaseArticleTextBlock {
            get {
                return ResourceManager.GetString("PurchaseArticleTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stavke.
        /// </summary>
        internal static string PurchaseBillItemsTextBlock {
            get {
                return ResourceManager.GetString("PurchaseBillItemsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racun.
        /// </summary>
        internal static string PurchasePriceTextBlock {
            get {
                return ResourceManager.GetString("PurchasePriceTextBlock", resourceCulture);
            }
        }
    }
}
